// resources/js/Components/NavBar.tsx
import React from 'react'
import { Link } from '@inertiajs/inertia-react'

const NavBar = () => {
  return (
    <div className=' w-screen sm:px-[10rem] px-[1rem] flex flex-row justify-between items-center h-[4rem] shadow-md'>
      <h1 className='sm:text-2xl text-lg font-[Poppins] font-bold'>Brand.</h1>
      <header className='flex flex-row font-[Poppins]'>
        <Link href="/home" className='w-[60px] hover:cursor-pointer hover:font-bold font-medium'>Home</Link>
        <Link href="/profile" className='w-[60px] hover:cursor-pointer hover:font-bold font-medium' >Profile</Link>
        <Link href="/signin" className='w-[60px] hover:cursor-pointer hover:font-bold font-medium'>Sign in</Link>
      </header>
    </div>
  )
}

export default NavBar

// resources/js/componenets/NavBar.vue
<template lang="">
   <div class="fixed w-full h-12 shadow-1xl bg-gray-100 z-20 flex items-center">
       <div class="container mx-auto flex flex-row items-center justify-between">
            <div class="ml-2">
            <h1 class=" text-indigo-600 md:text-3xl text-xl font-bold hover:cursor-pointer">Brand.</h1>
            </div>
            <nav>
                <ul class="flex flex-row items-center">
                    <router-link to="/login"><li class="px-3 mr-2 py-2 text-base font-medium hover:cursor-pointer">Login</li></router-link>
                    <router-link to="/register"><li class="px-3 mr-2 py-2 text-base font-medium hover:cursor-pointer">Register</li></router-link>
                </ul>
            </nav>
       </div>
   </div>
</template>

<script lang='ts'>
import {defineComponent, ref} from 'vue';
export default defineComponent({
    setup() {
        
    }
})
</script>
