// resources/js/componenets/NavBar.vue
<template lang="">
   <div class="fixed w-full h-12 shadow-1xl bg-gray-100 z-20 flex items-center">
       <div class="container mx-auto flex flex-row items-center justify-between">
            <div class="ml-2">
            <h1 class=" text-indigo-600 md:text-3xl text-xl font-bold hover:cursor-pointer">Brand.</h1>
            </div>
            <nav>
                <ul class="flex flex-row items-center">
                    <router-link to="/login"><li class="px-3 mr-2 py-2 text-base font-medium hover:cursor-pointer">Login</li></router-link>
                    <router-link to="/register"><li class="px-3 mr-2 py-2 text-base font-medium hover:cursor-pointer">Register</li></router-link>
                </ul>
            </nav>
       </div>
   </div>
</template>

<script lang='ts'>
import {defineComponent, ref} from 'vue';
export default defineComponent({
    setup() {
        
    }
})
</script>

// resources/js/components/nav/NavBar.tsx
import React from 'react'
import { Link } from '@inertiajs/inertia-react';

const Menu = () => {
  return (
    <div className='h-[4rem] shadow-md fixed w-screen bg-white'>
        <header>
          <nav className='sm:px-5 px-2 h-[4rem] items-center flex flex-row justify-between'>
            <div className='flex items-center flex-row'>
              <h1 className='sm:text-2xl text-md font-bold w-[3rem] mx-4'>Brand.</h1>
              <Link className='px-3 ml-9 font-medium' href="/home">Home</Link>
              <Link className='px-3 ml-3 font-medium' href="/profile">Profile</Link>
            </div>
            <div>
              <Link method='POST' href="/logout">Logout</Link>
            </div>
          </nav>
        </header>
    </div>
  )
}

export default Menu
